const movies = [
    "Snow White and the Seven Dwarfs",
    "Pinocchio",
    "Fantasia",
    "The Reluctant Dragon",
    "Dumbo",
    "Bambi",
    "Saludos Amigos",
    "The Three Caballeros",
    "Melody Time",
    "The Adventures of Ichabod and Mr. Toad",
    "Cinderella",
    "Alice in Wonderland",
    "Peter Pan",
    "Lady and the Tramp",
    "Sleeping Beauty",
    "Captain Marvel",
    "One Hundred and One Dalmatians",
    "The Parent Trap",
    "The Sword in the Stone",
    "Mary Poppins",
    "The Jungle Book",
    "The Love Bug",
    "The Aristocats",
    "Herbie Rides Again",
    "The Shaggy D.A.",
    "Freaky Friday",
    "The Many Adventures of Winnie the Pooh",
    "The Rescuers",
    "Herbie Goes to Monte Carlo",
    "Pete’s Dragon",
    "Herbie Goes Bananas",
    "The Fox and the Hound",
    "The Black Cauldron",
    "The Great Mouse Detective",
    "Who Framed Roger Rabbit",
    "Oliver & Company",
    "Honey, I Shrunk the Kids",
    "Turner & Hooch",
    "The Little Mermaid",
    "Ducktales",
    "The Rescuers Down Under",
    "Three Men and a Little Lady",
    "The Rocketeer",
    "Beauty and the Beast",
    "Sister Act",
    "Honey, I Blew Up the Kid",
    "The Mighty Ducks",
    "Aladdin",
    "The Muppet Christmas Carol",
    "Super Mario Bros.",
    "Hocus Pocus",
    "Cool Runnings",
    "The Nightmare Before Christmas",
    "Sister Act 2",
    "D2",
    "The Lion King",
    "The Santa Clause",
    "A Goofy Movie",
    "Pocahontas",
    "Toy Story",
    "Muppet Treasure Island",
    "James and the Giant Peach",
    "The Hunchback of Notre Dame",
    "D3",
    "101 Dalmatians [live action]",
    "Hercules",
    "George of the Jungle",
    "Air Bud",
    "Flubber",
    "Mulan",
    "The Parent Trap",
    "A Bug’s Life",
    "10 Things I Hate About You",
    "Tarzan",
    "Toy Story 2",
    "Fantasia/2000",
    "The Tigger Movie",
    "Dinosaur",
    "Remember the Titans",
    "102 Dalmatians",
    "The Emperor’s New Groove",
    "Recess",
    "Atlantis",
    "The Princess Diaries",
    "Monsters, Inc.",
    "Return to Never Land",
    "Lilo & Stitch",
    "Spirited Away",
    "Santa Clause 2",
    "Treasure Planet",
    "The Jungle Book 2",
    "Piglet’s Big Movie",
    "The Lizzie McGuire Movie",
    "Finding Nemo",
    "Pirates of the Caribbean",
    "Freaky Friday",
    "Brother Bear",
    "The Haunted Mansion",
    "The Young Black Stallion",
    "Confessions of a Teenage Drama Queen",
    "Home on the Range",
    "Around the World in 80 Days",
    "The Princess Diaries 2",
    "The Incredibles",
    "Pooh’s Heffalump Movie",
    "The Pacifier",
    "Ice Princess",
    "Howl’s Moving Castle",
    "Herbie",
    "Sky High",
    "Valiant",
    "Chicken Little",
    "The Chronicles of Narnia",
    "Eight Below",
    "The Wild",
    "Goal! The Dream Begins",
    "Cars",
    "Pirates of the Caribbean",
    "Invincible",
    "The Santa Clause 3",
    "Bridge to Terabithia",
    "Meet the Robinsons",
    "Pirates of the Caribbean",
    "Ratatouille",
    "The Secret of the Magic Gourd",
    "Underdog",
    "The Game Plan",
    "Enchanted",
    "Hannah Montana & Miley Cyrus",
    "The Chronicles of Narnia",
    "Tinker Bell",
    "Beverly Hills Chihuahua",
    "High School Musical 3",
    "Bolt",
    "Bedtime Stories",
    "Jonas Brothers",
    "Race to Witch Mountain",
    "Hannah Montana the Movie",
    "Up",
    "G-Force",
    "Ponyo",
    "Tinker Bell and the Lost Treasure",
    "Disney’s A Christmas Carol",
    "The Princess and the Frog",
    "Alice in Wonderland",
    "Prince of Persia",
    "Toy Story 3",
    "The Sorcerer’s Apprentice",
    "Tales from Earthsea",
    "Tinker Bell and the Great Fairy Rescue",
    "Secretariat",
    "Tangled",
    "Gnomeo & Juliet",
    "Mars Needs Moms",
    "Prom",
    "Pirates of the Caribbean",
    "Cars 2",
    "Real Steel",
    "The Muppets",
    "War Horse",
    "The Secret World of Arrietty",
    "John Carter",
    "Marvel’s The Avengers",
    "Brave",
    "The Odd Life of Timothy Green",
    "Secret of the Wings",
    "Frankenweenie",
    "Wreck-It Ralph",
    "Oz the Great and Powerful",
    "Iron Man 3",
    "Monsters University",
    "The Lone Ranger",
    "Planes",
    "The Wind Rises",
    "Thor",
    "Frozen",
    "Saving Mr. Banks",
    "The Pirate Fairy",
    "Muppets Most Wanted",
    "Captain America",
    "Bears",
    "Million Dollar Arm",
    "Maleficent",
    "Planes",
    "Guardians of the Galaxy",
    "The Hundred-Foot Journey",
    "Alexander and the Terrible, Horrible, No Good, Very Bad Day",
    "Big Hero 6",
    "Into The Woods",
    "Tinker Bell and the Legend of the NeverBeast",
    "McFarland, USA",
    "Cinderella",
    "Avengers",
    "Tomorrowland",
    "Inside Out",
    "Ant-Man",
    "The Good Dinosaur",
    "Star Wars",
    "Zootopia",
    "The Jungle Book",
    "Captain America",
    "Alice Through the Looking Glass",
    "Finding Dory",
    "The BFG",
    "Pete’s Dragon",
    "Queen of Katwe",
    "Doctor Strange",
    "Moana",
    "Rogue One",
    "Beauty and the Beast",
    "Guardians of the Galaxy, Vol. 2",
    "Pirates of the Caribbean",
    "Cars 3",
    "Thor",
    "Coco",
    "Robin Hood",
    "Star Wars",
    "Black Panther",
    "A Wrinkle in Time",
    "Avengers",
    "Incredibles 2",
    "Ant-Man and The Wasp",
    "Christopher Robin",
    "The Nutcracker and the Four Realms",
    "Ralph Breaks the Internet",
    "Mary Poppins Returns",
    "Dumbo",
    "Avengers",
    "Aladdin",
    "Toy Story 4",
    "The Lion King",
    "Maleficent",
    "Lady and the Tramp",
    "Noelle",
    "Star Wars",
    "Onward",
    "Stargirl",
    "Artemis Fowl",
    "Hamilton",
    "Mulan",
    "Soul",
    "Raya and the Last Dragon",
    "Cruella",
    "Luca",
    "Black Widow",
    "Jungle Cruise",
    "Shang-Chi and the Legend of the Ten Rings",
    "Eternals",
    "Encanto",
    "Diary of a Wimpy Kid",
    "The Ice Age Adventures of Buck Wild",
    "Turning Red",
    "Cheaper by the Dozen",
    "Doctor Strange in the Multiverse of Madness",
    "Chip ’n Dale",
    "Lightyear",
    "Thor",
    "Pinocchio",
    "Hocus Pocus 2",
    "Black Panther",
    "Strange World",
    "Disenchanted",
    "Diary of a Wimpy Kid",
    "Night at the Museum",
    "Ant-Man and the Wasp",
    "Peter Pan & Wendy",
    "Guardians of the Galaxy Vol. 3",
    "The Little Mermaid",
    "Elemental",
    "Indiana Jones and the Dial of Destiny",
    "Haunted Mansion",
    "The Marvels",
    "Wish",
    "Diary of a Wimpy Kid Christmas",
];

export default movies;
