const movies = [
    "Snow White and the Seven Dwarfs",
    "Pinocchio",
    "Fantasia",
    "The Reluctant Dragon",
    "Dumbo",
    "Bambi",
    "Saludos Amigos",
    "Victory Through Air Power",
    "The Three Caballeros",
    "Make Mine Music",
    "Song of the South",
    "Fun and Fancy Free",
    "Melody Time",
    "So Dear to My Heart",
    "The Adventures of Ichabod and Mr. Toad",
    "Cinderella",
    "Treasure Island",
    "Alice in Wonderland",
    "The Story of Robin Hood and His Merrie Men",
    "Peter Pan",
    "The Sword and the Rose",
    "The Living Desert",
    "Rob Roy, the Highland Rogue",
    "The Vanishing Prairie",
    "20,000 Leagues Under the Sea",
    "Davy Crockett, King of the Wild Frontier",
    "Lady and the Tramp",
    "The African Lion",
    "The Littlest Outlaw",
    "The Great Locomotive Chase",
    "Davy Crockett and the River Pirates",
    "Secrets of Life",
    "Westward Ho the Wagons!",
    "Johnny Tremain",
    "Perri",
    "Old Yeller",
    "The Light in the Forest",
    "White Wilderness",
    "Tonka",
    "Sleeping Beauty",
    "The Shaggy Dog",
    "Darby O’Gill and the Little People",
    "Third Man on the Mountain",
    "Toby Tyler, or Ten Weeks with a Circus",
    "Kidnapped",
    "Pollyanna",
    "The Sign of Zorro",
    "Jungle Cat",
    "Ten Who Dared",
    "Swiss Family Robinson",
    "One Hundred and One Dalmatians",
    "The Absent-Minded Professor",
    "The Parent Trap",
    "Nikki, Wild Dog of the North",
    "Greyfriars Bobby",
    "Babes in Toyland",
    "Moon Pilot",
    "Bon Voyage",
    "Big Red",
    "Almost Angels",
    "The Legend of Lobo",
    "In Search of the Castaways",
    "Son of Flubber",
    "Miracle of the White Stallions",
    "Savage Sam",
    "Summer Magic",
    "The Incredible Journey",
    "The Sword in the Stone",
    "The Three Lives of Thomasina",
    "The Misadventures of Merlin Jones",
    "A Tiger Walks",
    "The Moon-Spinners",
    "Mary Poppins",
    "Emil and the Detectives",
    "Those Calloways",
    "The Monkey’s Uncle",
    "That Darn Cat!",
    "The Ugly Dachshund",
    "Lt. Robin Crusoe U.S.N.",
    "The Fighting Prince of Donegal",
    "Follow Me, Boys!",
    "Monkeys, Go Home!",
    "The Adventures of Bullwhip Griffin",
    "The Happiest Millionaire",
    "The Gnome-Mobile",
    "The Jungle Book",
    "Charlie, The Lonesome Cougar",
    "Blackbeard’s Ghost",
    "The One and Only, Genuine, Original Family Band",
    "Never a Dull Moment",
    "The Horse in the Gray Flannel Suit",
    "The Love Bug",
    "Smith!",
    "Rascal",
    "The Computer Wore Tennis Shoes",
    "King of the Grizzlies",
    "The Boatniks",
    "The Aristocats",
    "The Wild Country",
    "The Barefoot Executive",
    "Scandalous John",
    "The $1,000,000 Duck",
    "Bedknobs and Broomsticks",
    "The Biscuit Eater",
    "Napoleon and Samantha",
    "Now You See Him, Now You Don’t",
    "Run, Cougar, Run",
    "Snowball Express",
    "The World’s Greatest Athlete",
    "Charley and the Angel",
    "One Little Indian",
    "Robin Hood",
    "Superdad",
    "Herbie Rides Again",
    "The Bears and I",
    "The Castaway Cowboy",
    "The Island at the Top of the World",
    "The Strongest Man in the World",
    "Escape to Witch Mountain",
    "The Apple Dumpling Gang",
    "One of Our Dinosaurs is Missing",
    "The Best of Walt Disney’s True-Life Adventures",
    "Ride a Wild Pony",
    "No Deposit, No Return",
    "Gus",
    "Treasure of Matecumbe",
    "The Shaggy D.A.",
    "Freaky Friday",
    "The Littlest Horse Thieves",
    "The Many Adventures of Winnie the Pooh",
    "The Rescuers",
    "Herbie Goes to Monte Carlo",
    "Pete’s Dragon",
    "Candleshoe",
    "Return from Witch Mountain",
    "The Cat from Outer Space",
    "Hot Lead and Cold Feet",
    "The North Avenue Irregulars",
    "The Apple Dumpling Gang Rides Again",
    "Unidentified Flying Oddball",
    "The Black Hole",
    "Midnight Madness",
    "The Last Flight of Noah’s Ark",
    "Herbie Goes Bananas",
    "The Devil and Max Devlin",
    "Amy",
    "The Fox and the Hound",
    "Condorman",
    "The Watcher in the Woods",
    "Night Crossing",
    "Tron",
    "Tex",
    "Trenchcoat",
    "Something Wicked This Way Comes",
    "Never Cry Wolf",
    "Splash",
    "Tiger Town",
    "Country",
    "Baby...Secret of the Lost Legend",
    "Return to Oz",
    "The Black Cauldron",
    "My Science Project",
    "The Journey of Natty Gann",
    "One Magic Christmas",
    "Down and Out in Beverly Hills",
    "Off Beat",
    "Ruthless People",
    "The Great Mouse Detective",
    "Flight of the Navigator",
    "Tough Guys",
    "The Color of Money",
    "Outrageous Fortune",
    "Tin Men",
    "Ernest Goes to Camp",
    "Benji the Hunted",
    "Adventures in Babysitting",
    "Stakeout",
    "Can’t Buy Me Love",
    "Hello Again",
    "Three Men and a Baby",
    "Good Morning, Vietnam",
    "Shoot to Kill",
    "D.O.A.",
    "Return to Snowy River",
    "Big Business",
    "Who Framed Roger Rabbit",
    "Cocktail",
    "The Rescue",
    "Heartbreak Hotel",
    "The Good Mother",
    "Ernest Saves Christmas",
    "Oliver & Company",
    "Beaches",
    "Three Fugitives",
    "New York Stories",
    "Disorganized Crime",
    "Dead Poets Society",
    "Honey, I Shrunk the Kids",
    "Turner & Hooch",
    "Cheetah",
    "An Innocent Man",
    "Gross Anatomy",
    "The Little Mermaid",
    "Blaze",
    "Stella",
    "Where the Heart Is",
    "Pretty Woman",
    "Ernest Goes to Jail",
    "Spaced Invaders",
    "Fire Birds",
    "Dick Tracy",
    "Betsy’s Wedding",
    "Arachnophobia",
    "Ducktales",
    "Taking Care of Business",
    "Mr. Destiny",
    "The Rescuers Down Under",
    "Three Men and a Little Lady",
    "Green Card",
    "White Fang",
    "Run",
    "Scenes from a Mall",
    "Shipwrecked",
    "The Marrying Man",
    "Oscar",
    "One Good Cop",
    "What About Bob?",
    "Wild Hearts Can’t Be Broken",
    "The Rocketeer",
    "The Doctor",
    "V. I. Warshawski",
    "True Identity",
    "Paradise",
    "Deceived",
    "Ernest Scared Stupid",
    "Billy Bathgate",
    "Beauty and the Beast",
    "Father of the Bride",
    "The Hand That Rocks the Cradle",
    "Medicine Man",
    "Blame It On The Bellboy",
    "Noises Off",
    "Straight Talk",
    "Newsies",
    "Passed Away",
    "Encino Man",
    "Sister Act",
    "Honey, I Blew Up the Kid",
    "A Stranger Among Us",
    "3 Ninjas",
    "The Gun in Betty Lou’s Handbag",
    "Crossing the Bridge",
    "Sarafina!",
    "Captain Ron",
    "The Mighty Ducks",
    "Consenting Adults",
    "Aladdin",
    "The Distinguished Gentleman",
    "The Muppet Christmas Carol",
    "Alive",
    "Aspen Extreme",
    "The Cemetery Club",
    "Homeward Bound",
    "Swing Kids",
    "A Far Off Place",
    "Born Yesterday",
    "Adventures of Huck Finn",
    "Indian Summer",
    "Bound by Honor",
    "Super Mario Bros.",
    "Guilty as Sin",
    "Life with Mikey",
    "What’s Love Got to Do with It",
    "Son-In-Law",
    "Hocus Pocus",
    "Another Stakeout",
    "My Boyfriend’s Back",
    "Father Hood",
    "The Joy Luck Club",
    "Money for Nothing",
    "The Program",
    "Cool Runnings",
    "The Nightmare Before Christmas",
    "The Three Musketeers",
    "Sister Act 2",
    "Tombstone",
    "Cabin Boy",
    "The Air Up There",
    "Iron Will",
    "My Father the Hero",
    "Blank Check",
    "Angie",
    "The Ref",
    "D2",
    "Holy Matrimony",
    "White Fang 2",
    "The Inkwell",
    "When a Man Loves a Woman",
    "Renaissance Man",
    "The Lion King",
    "I Love Trouble",
    "Angels in the Outfield",
    "In the Army Now",
    "Color of Night",
    "It's Pat",
    "Camp Nowhere",
    "A Simple Twist of Fate",
    "Quiz Show",
    "Terminal Velocity",
    "Ed Wood",
    "Robert A. Heinlein's The Puppet Masters",
    "Squanto",
    "The Santa Clause",
    "A Low Down Dirty Shame",
    "Rudyard Kipling's The Jungle Book",
    "Houseguest",
    "Bad Company",
    "Miami Rhapsody",
    "The Jerky Boys",
    "Heavyweights",
    "Man of the House",
    "Roommates",
    "Tall Tale",
    "Funny Bones",
    "Jefferson in Paris",
    "A Goofy Movie",
    "While You Were Sleeping",
    "A Pyromaniac's Love Story",
    "Crimson Tide",
    "Mad Love",
    "Pocahontas",
    "Judge Dredd",
    "Operation Dumbo Drop",
    "Dangerous Minds",
    "A Kid in King Arthur's Court",
    "The Tie that Binds",
    "Unstrung Heroes",
    "The Big Green",
    "Dead Presidents",
    "Feast of July",
    "The Scarlet Letter",
    "Frank and Ollie",
    "Powder",
    "Toy Story",
    "Father of the Bride, Part II",
    "Nixon",
    "Tom and Huck",
    "Mr. Holland's Opus",
    "White Squall",
    "Mr. Wrong",
    "Muppet Treasure Island",
    "Before and After",
    "Up Close and Personal",
    "Homeward Bound II",
    "Two Much",
    "Little Indian, Big City",
    "James and the Giant Peach",
    "Celtic Pride",
    "Last Dance",
    "Boys",
    "Spy Hard",
    "Eddie",
    "The Rock",
    "The Hunchback of Notre Dame",
    "Phenomenon",
    "Kazaam",
    "Jack",
    "First Kid",
    "The Rich Man's Wife",
    "D3",
    "The Associate",
    "Ransom",
    "The War at Home",
    "101 Dalmatians [live action]",
    "The Preacher's Wife",
    "Evita",
    "Metro",
    "Prefontaine",
    "Shadow Conspiracy",
    "That Darn Cat [remake]",
    "Jungle 2 Jungle",
    "The Sixth Man",
    "Grosse Pointe Blank",
    "Romy and Michele's High School Reunion",
    "Gone Fishin'",
    "Con Air",
    "Hercules",
    "George of the Jungle",
    "Nothing to Lose",
    "Air Bud",
    "G.I. Jane",
    "A Thousand Acres",
    "Washington Square",
    "RocketMan",
    "Playing God",
    "Flubber",
    "An American Werewolf in Paris",
    "Mr. Magoo",
    "Kundun",
    "Deep Rising",
    "Krippendorf’s Tribe",
    "An Alan Smithee Film",
    "Meet the Deedles",
    "He Got Game",
    "The Horse Whisperer",
    "Six Days, Seven Nights",
    "Mulan",
    "Armageddon",
    "Jane Austen’s Mafia!",
    "The Parent Trap",
    "Firelight",
    "Simon Birch",
    "Holy Man",
    "Beloved",
    "The Waterboy",
    "I’ll Be Home for Christmas",
    "Enemy of the State",
    "A Bug’s Life",
    "Mighty Joe Young",
    "A Civil Action",
    "Rushmore",
    "My Favorite Martian",
    "The Other Sister",
    "Doug’s 1st Movie",
    "10 Things I Hate About You",
    "Endurance",
    "Instinct",
    "Tarzan",
    "Summer of Sam",
    "Inspector Gadget",
    "The Sixth Sense",
    "The 13th Warrior",
    "Breakfast of Champions",
    "Mumford",
    "Mystery Alaska",
    "The Hand Behind the Mouse",
    "The Straight Story",
    "The Insider",
    "Toy Story 2",
    "Deuce Bigalow",
    "Cradle Will Rock",
    "Bicentennial Man",
    "Fantasia/2000",
    "Play It to the Bone",
    "Gun Shy",
    "The Tigger Movie",
    "Mission to Mars",
    "Whispers",
    "High Fidelity",
    "Keeping the Faith",
    "Dinosaur",
    "Shanghai Noon",
    "Gone in 60 Seconds",
    "Disney’s The Kid",
    "Coyote Ugly",
    "The Crew",
    "Duets",
    "Remember the Titans",
    "Playing Mona Lisa",
    "Unbreakable",
    "102 Dalmatians",
    "The Emperor’s New Groove",
    "O Brother, Where Art Thou?",
    "Double Take",
    "Recess",
    "Just Visiting",
    "Pearl Harbor",
    "Atlantis",
    "crazy/beautiful",
    "The Princess Diaries",
    "Bubble Boy",
    "New Port South",
    "Max Keeble’s Big Move",
    "Corky Romano",
    "High Heels and Low Lifes",
    "Monsters, Inc.",
    "Out Cold",
    "The Royal Tenenbaums",
    "Snow Dogs",
    "The Count of Monte Cristo",
    "Return to Never Land",
    "Sorority Boys",
    "The Rookie",
    "Big Trouble",
    "Frank McKlusky, C.I.",
    "ESPN’s Ultimate X",
    "Bad Company",
    "Lilo & Stitch",
    "Reign of Fire",
    "The Country Bears",
    "Signs",
    "Spirited Away",
    "Moonlight Mile",
    "Sweet Home Alabama",
    "Tuck Everlasting",
    "Santa Clause 2",
    "Treasure Planet",
    "The Hot Chick",
    "25th Hour",
    "The Recruit",
    "Shanghai Knights",
    "The Jungle Book 2",
    "Bringing Down the House",
    "Piglet’s Big Movie",
    "Ghosts of the Abyss",
    "Holes",
    "The Lizzie McGuire Movie",
    "Finding Nemo",
    "Pirates of the Caribbean",
    "Freaky Friday",
    "Open Range",
    "Hope Springs",
    "Cold Creek Manor",
    "Under the Tuscan Sun",
    "Veronica Guerin",
    "Brother Bear",
    "The Haunted Mansion",
    "Calendar Girls",
    "The Young Black Stallion",
    "Teacher’s Pet",
    "Miracle",
    "Confessions of a Teenage Drama Queen",
    "Hidalgo",
    "The Ladykillers",
    "Home on the Range",
    "The Alamo",
    "Sacred Planet",
    "Raising Helen",
    "Around the World in 80 Days",
    "America’s Heart & Soul",
    "King Arthur",
    "The Village",
    "The Princess Diaries 2",
    "Mr. 3000",
    "The Last Shot",
    "Ladder 49",
    "The Incredibles",
    "National Treasure",
    "The Life Aquatic with Steve Zissou",
    "Aliens of the Deep",
    "Pooh’s Heffalump Movie",
    "The Pacifier",
    "Ice Princess",
    "A Lot Like Love",
    "The Hitchhiker’s Guide to the Galaxy",
    "Howl’s Moving Castle",
    "Herbie",
    "Dark Water",
    "Sky High",
    "Valiant",
    "Flightplan",
    "The Greatest Game Ever Played",
    "Shopgirl",
    "Chicken Little",
    "The Chronicles of Narnia",
    "Casanova",
    "Glory Road",
    "Annapolis",
    "Roving Mars",
    "Eight Below",
    "The Shaggy Dog",
    "Stay Alive",
    "The Wild",
    "Stick It",
    "Goal! The Dream Begins",
    "Cars",
    "Pirates of the Caribbean",
    "Step Up",
    "Invincible",
    "The Guardian",
    "The Prestige",
    "The Santa Clause 3",
    "Déjà Vu",
    "Apocalypto",
    "Primeval",
    "Bridge to Terabithia",
    "Wild Hogs",
    "Meet the Robinsons",
    "The Invisible",
    "Pirates of the Caribbean",
    "Ratatouille",
    "The Secret of the Magic Gourd",
    "Underdog",
    "The Game Plan",
    "Dan in Real Life",
    "Le Premier Cri",
    "Enchanted",
    "National Treasure",
    "Hannah Montana & Miley Cyrus",
    "Step Up 2 the Streets",
    "College Road Trip",
    "The Chronicles of Narnia",
    "WALL•E",
    "Swing Vote",
    "Tinker Bell",
    "Miracle at St. Anna",
    "Beverly Hills Chihuahua",
    "Morning Light",
    "High School Musical 3",
    "Roadside Romeo",
    "Bolt",
    "Bedtime Stories",
    "Confessions of a Shopaholic",
    "Hexe Lilli",
    "Jonas Brothers",
    "Race to Witch Mountain",
    "Hannah Montana the Movie",
    "Earth",
    "Trail of the Panda",
    "The Boys",
    "Up",
    "The Proposal",
    "G-Force",
    "Ponyo",
    "X-Games 3D",
    "Walt & El Grupo",
    "Surrogates",
    "Tinker Bell and the Lost Treasure",
    "Kniga Masterov",
    "Disney’s A Christmas Carol",
    "Old Dogs",
    "The Princess and the Frog",
    "When in Rome",
    "Alice in Wonderland",
    "Waking Sleeping Beauty",
    "The Last Song",
    "Oceans",
    "Prince of Persia",
    "Toy Story 3",
    "The Sorcerer’s Apprentice",
    "Step Up 3D",
    "Tales from Earthsea",
    "The Switch",
    "Tinker Bell and the Great Fairy Rescue",
    "You Again",
    "Secretariat",
    "Do Dooni Chaar",
    "Tangled",
    "The Tempest",
    "Tron",
    "Anaganaga O Dheerudu",
    "Gnomeo & Juliet",
    "Hexe Lilli",
    "I Am Number Four",
    "Mars Needs Moms",
    "African Cats",
    "Zokkomon",
    "Prom",
    "Pirates of the Caribbean",
    "Cars 2",
    "Winnie the Pooh",
    "The Help",
    "Fright Night",
    "Real Steel",
    "The Muppets",
    "War Horse",
    "The Secret World of Arrietty",
    "John Carter",
    "Arjun",
    "Chimpanzee",
    "Marvel’s The Avengers",
    "Brave",
    "Mad Buddies",
    "People Like Us",
    "The Odd Life of Timothy Green",
    "Secret of the Wings",
    "Barfi!",
    "Frankenweenie",
    "Wreck-It Ralph",
    "Lincoln",
    "Oz the Great and Powerful",
    "Wings of Life",
    "Iron Man 3",
    "Monsters University",
    "The Lone Ranger",
    "Planes",
    "The Fifth Estate",
    "The Wind Rises",
    "Thor",
    "Delivery Man",
    "Frozen",
    "Saving Mr. Banks",
    "Schuks! Your Country Needs You",
    "The Pirate Fairy",
    "Need for Speed",
    "Muppets Most Wanted",
    "Captain America",
    "Bears",
    "Million Dollar Arm",
    "Maleficent",
    "Planes",
    "Guardians of the Galaxy",
    "The Hundred-Foot Journey",
    "Khoobsurat",
    "Alexander and the Terrible, Horrible, No Good, Very Bad Day",
    "Big Hero 6",
    "Into The Woods",
    "Strange Magic",
    "Tinker Bell and the Legend of the NeverBeast",
    "McFarland, USA",
    "Cinderella",
    "Monkey Kingdom",
    "Tini",
    "Avengers",
    "Tomorrowland",
    "Inside Out",
    "ABCD2",
    "Ant-Man",
    "Schuks! Pay Back the Money!",
    "Bridge of Spies",
    "The Good Dinosaur",
    "Star Wars",
    "The Finest Hours",
    "Zootopia",
    "The Jungle Book",
    "Captain America",
    "Alice Through the Looking Glass",
    "Finding Dory",
    "The BFG",
    "Pete’s Dragon",
    "The Light Between Oceans",
    "Queen of Katwe",
    "Doctor Strange",
    "Moana",
    "Rogue One",
    "Dangal",
    "Beauty and the Beast",
    "Born in China",
    "Guardians of the Galaxy, Vol. 2",
    "Pirates of the Caribbean",
    "Cars 3",
    "Jagga Jasoos",
    "Posledny bogatyr",
    "Thor",
    "Coco",
    "Star Wars",
    "Black Panther",
    "A Wrinkle in Time",
    "Avengers",
    "Solo",
    "Incredibles 2",
    "Ant-Man and The Wasp",
    "Christopher Robin",
    "The Nutcracker and the Four Realms",
    "Ralph Breaks the Internet",
    "Mary Poppins Returns",
    "Captain Marvel",
    "Dumbo",
    "Penguins",
    "Avengers",
    "Aladdin",
    "Toy Story 4",
    "The Lion King",
    "Maleficent",
    "Lady and the Tramp",
    "Noelle",
    "Frozen 2",
    "Star Wars",
    "Togo",
    "Timmy Failure",
    "Onward",
    "Stargirl",
    "Dolphin Reef",
    "Elephant",
    "Artemis Fowl",
    "Hamilton",
    "Magic Camp",
    "The One and Only Ivan",
    "Mulan",
    "Godmothered",
    "Safety",
    "Soul",
    "Posledny bogatyr",
    "Flora & Ulysses",
    "Raya and the Last Dragon",
    "Cruella",
    "Luca",
    "Black Widow",
    "Jungle Cruise",
    "Shang-Chi and the Legend of the Ten Rings",
    "Eternals",
    "Encanto",
    "Diary of a Wimpy Kid",
    "Posledny bogatyr",
    "The Ice Age Adventures of Buck Wild",
    "The Beatles",
    "Turning Red",
    "Cheaper by the Dozen",
    "Better Nate Than Ever",
    "Polar Bear",
    "Doctor Strange in the Multiverse of Madness",
    "Chip ’n Dale",
    "Hollywood Stargirl",
    "Lightyear",
    "Rise",
    "Thor",
    "Mija",
    "Pinocchio",
    "Hocus Pocus 2",
    "Black Panther",
    "Strange World",
    "Disenchanted",
    "Diary of a Wimpy Kid",
    "Night at the Museum",
    "Ant-Man and the Wasp",
    "Chang Can Dunk",
    "Peter Pan & Wendy",
    "Guardians of the Galaxy Vol. 3",
    "Crater",
    "The Little Mermaid",
    "Elemental",
    "World’s Best",
    "Indiana Jones and the Dial of Destiny",
    "Haunted Mansion",
    "The Marvels",
    "Dashing Through the Snow",
    "Wish",
    "Diary of a Wimpy Kid Christmas"
];

export default movies;
