const movies = [
    "Eight Below",
    "Brave",
    "Luca",
    "Lemonade Mouth",
    "A Bug's Life",
    "Encanto",
    "A Goofy Movie",
    "WALL-E",
    "Turning Red",
    "Peter Pan",
    "Fantasia 2000",
    "The Tigger Movie",
    "The Aristocats",
    "The Princess Diaries",
    "Den Brother",
    "Robin Hood",
    "Read It and Weep",
    "G-Force",
    "Bedtime Stories",
    "Finding Nemo",
    "Pocahontas",
    "Mary Poppins",
    "The Lizzie McGuire Movie",
    "Sharpay's Fabulous Adventure",
    "101 Dalmatians [live action]",
    "Honey, I Shrunk the Kids",
    "Toy Story 3",
    "Cruella",
    "The Incredibles",
    "Pirates of the Caribbean: Dead Man's Chest",
    "Camp Rock",
    "Jungle Cruise",
    "The Odd Life of Timothy Green",
    "Aladdin",
    "Sky High",
    "Dinosaur",
    "Tarzan",
    "The Haunted Mansion",
    "Winnie the Pooh",
    "Meet the Robinsons",
    "The Santa Clause 3: The Escape Clause",
    "Mary Poppins Returns",
    "Underdog",
    "Princess Protection Program",
    "Toy Story 2",
    "Saving Mr. Banks",
    "The BFG",
    "John Carter",
    "Bolt",
    "Lilo & Stitch",
    "The Princess and the Frog",
    "Race to Witch Mountain",
    "Tangled",
    "The Rescuers",
    "Tinker Bell and the Legend of the NeverBeast",
    "The Princess Diaries 2",
    "The Santa Clause",
    "The Sword in the Stone",
    "Air Bud",
    "Tomorrowland",
    "The Pirate Fairy",
    "Elemental",
    "Return to Never Land",
    "Disenchanted",
    "Planes",
    "Alice in Wonderland",
    "Wish",
    "Brother Bear",
    "The Lion King",
    "Snow White and the Seven Dwarfs",
    "Toy Story",
    "Cinderella",
    "Oliver & Company",
    "Descendants",
    "High School Musical",
    "Beauty and the Beast",
    "Ratatouille",
    "Toy Story 4",
    "Incredibles 2",
    "Mulan",
    "Home on the Range",
    "The Great Mouse Detective",
    "Hercules",
    "Bambi",
    "The Sorcerer's Apprentice",
    "Hannah Montana: The Movie",
    "Up",
    "The Muppet Christmas Carol",
    "Christopher Robin",
    "The Little Mermaid",
    "Tron: Legacy",
    "The Hunchback of Notre Dame",
    "Strange World",
    "The Nutcracker and the Four Realms",
    "The Nightmare Before Christmas",
    "Lady and the Tramp",
    "Prince of Persia",
    "Starstruck",
    "Chip ’n Dale",
    "Ducktales",
    "Inside Out",
    "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe",
    "Muppet Treasure Island",
    "High School Musical 3",
    "Into The Woods",
    "High School Musical 2",
    "Piglet’s Big Movie",
    "The Rescuers Down Under",
    "Finding Dory",
    "Pirates of the Caribbean: At World's End",
    "Wizards of Waverly Place: The Movie",
    "Alice Through the Looking Glass",
    "Fantasia",
    "Frozen",
    "Hatching Pete",
    "The Fox and the Hound",
    "Who Framed Roger Rabbit",
    "Pirates of the Caribbean: The Curse of the Black Pearl",
    "George of the Jungle",
    "The Parent Trap",
    "The Chronicles of Narnia: Prince Caspian",
    "Maleficent: Mistress of Evil",
    "Around the World in 80 Days",
    "Atlantis",
    "Halloweentown II: Kalabar's Revenge",
    "Zootopia",
    "The Suite Life Movie",
    "Pirates of the Caribbean: On Stranger Tides",
    "Ralph Breaks the Internet",
    "Freaky Friday",
    "Sleeping Beauty",
    "The Emperor's New Groove",
    "Confessions of a Teenage Drama Queen",
    "Oz the Great and Powerful",
    "Moana",
    "Monsters University",
    "Lightyear",
    "Camp Rock 2: The Final Jam",
    "Dumbo",
    "Onward",
    "The Game Plan",
    "Pooh’s Heffalump Movie",
    "Return to Halloweentown",
    "Frankenweenie",
    "The Black Cauldron",
    "Into the Woods",
    "The Pacifier",
    "The Shaggy Dog",
    "The Cheetah Girls",
    "Beverly Hills Chihuahua",
    "Soul",
    "Big Hero 6",
    "Wreck-It Ralph",
    "Teen Beach Movie",
    "Hocus Pocus 2",
    "Herbie Fully Loaded",
    "Cars",
    "Teen Beach 2",
    "101 Dalmatians",
    "Coco",
    "Ice Princess",
    "Disney’s A Christmas Carol",
    "Santa Clause 2",
    "The Lone Ranger",
    "Hamilton",
    "Twitches",
    "Haunted Mansion",
    "Raya and the Last Dragon",
    "Treasure Planet",
    "Tinker Bell and the Great Fairy Rescue",
    "Jump In!",
    "Muppets Most Wanted",
    "Chicken Little",
    "Pirates of the Caribbean: Dead Men Tell No Tales",
    "Hocus Pocus",
    "Enchanted",
    "Cars 3",
    "The Muppets",
    "Cars 2",
    "The Chronicles of Narnia: The Voyage of the Dawn Treader",
    "Noelle",
    "Frozen II",
    "Tinker Bell",
    "Pinocchio",
    "The Many Adventures of Winnie the Pooh",
    "Monsters, Inc.",
    "The Princess Diaries 2: Royal Engagement",
    "Tinker Bell and the Lost Treasure",
    "Twitches Too",
    "The Jungle Book",
    "Radio Rebel",
    "The Love Bug",
    "James and the Giant Peach",
    "Secret of the Wings",
    "The Good Dinosaur",
    "Adventures in Babysitting",
    "Maleficent",
    "Halloweentown High",
    "Halloweentown",
    "Good Luck Charlie, It's Christmas!",
    "Flubber"
];

export default movies;
